/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory.view;
    
import dao.BaseDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Allan Jay Aya-ay
 */
public class ViewItem extends javax.swing.JFrame {
    private Connection conn = null;
    private PreparedStatement ps = null;
    private ResultSet rs = null;
    private String itemCode;
    // Logged in User
    private String currentUser;
    
    /**
     * Creates new form ViewItem
     */
    public ViewItem() {
        initComponents();
        btnDeleteItem.setEnabled(false);
        btnEditItem.setEnabled(false);
        btnIncrease.setEnabled(false);
        btnDecrease.setEnabled(false);
    }
    
    private void populateTable(){
        try{
            ps = conn.prepareStatement("SELECT ItemID, Name, Description, Quantity, UnitOfMeasure"
                    + ", Category, UnitPrice FROM tblAddItem");
            rs = ps.executeQuery();
            
            tblItems.setModel(DbUtils.resultSetToTableModel(rs));
            
            ps.close();
            rs.close();
        }catch(Exception ex){
            System.out.println(ex);
        }
         
    }
    
    private void searchItemID(){
        String sql = "SELECT * FROM tblAddItem WHERE ItemID LIKE ?";
        
        try{
            ps = conn.prepareStatement(sql);
            ps.setString(1, txtSearch.getText() + "%");
            rs = ps.executeQuery();
            tblItems.setModel(DbUtils.resultSetToTableModel(rs));
            ps.close();
            rs.close();
        }catch(Exception e){
            System.out.println(e);
        }
    }
    private void searchName(){
        String sql = "SELECT * FROM tblAddItem WHERE Name LIKE ?";
        
        try{
            ps = conn.prepareStatement(sql);
            ps.setString(1, txtSearch.getText() + "%");
            rs = ps.executeQuery();
            tblItems.setModel(DbUtils.resultSetToTableModel(rs));
            ps.close();
            rs.close();
        }catch(Exception e){
            System.out.println(e);
        }
    }
    private void searchDescription(){
        String sql = "SELECT * FROM tblAddItem WHERE Description LIKE ?";
        
        try{
            ps = conn.prepareStatement(sql);
            ps.setString(1, txtSearch.getText() + "%");
            rs = ps.executeQuery();
            tblItems.setModel(DbUtils.resultSetToTableModel(rs));
            ps.close();
            rs.close();
        }catch(Exception e){
            System.out.println(e);
        }
    }
    private void searchCategory(){//<editor-fold defaultstate="collapsed" desc="comment">
        String sql = "SELECT * FROM tblAddItem WHERE Category LIKE ?";
        
        try{
            ps = conn.prepareStatement(sql);
            ps.setString(1, txtSearch.getText() + "%");
            rs = ps.executeQuery();
            tblItems.setModel(DbUtils.resultSetToTableModel(rs));
            ps.close();
            rs.close();
        }catch(Exception e){
            System.out.println(e);
        }
       
    }
    //</editor-fold> 
    
    private void placeToItemInfo(){//<editor-fold defaultstate="collapsed" desc="comment">
        int row = tblItems.getSelectedRow();
        
        lblItemID.setText(tblItems.getModel().getValueAt(row, 0).toString());
        lblCategory.setText(tblItems.getModel().getValueAt(row, 5).toString());
        lblQuantity.setText(tblItems.getModel().getValueAt(row, 3).toString());
        lblName.setText(tblItems.getModel().getValueAt(row, 1).toString());
        lblDescription.setText(tblItems.getModel().getValueAt(row, 2).toString());
        lblPrice.setText(tblItems.getModel().getValueAt(row, 6).toString());
    }
    //</editor-fold>
    
    private void deleteItem(){
        String sql = "DELETE FROM tblAddItem WHERE ItemID = ?";
        
        try{
            
            ps = conn.prepareStatement(sql);
            ps.setString(1, lblItemID.getText());
            ps.execute();
            JOptionPane.showMessageDialog(null, "Item Deleted");
            
        }catch(Exception e){
            System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupSearch = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        radBtnItemID = new javax.swing.JRadioButton();
        radBtnName = new javax.swing.JRadioButton();
        radBtnDescription = new javax.swing.JRadioButton();
        radBtnCategory = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblItemID = new javax.swing.JLabel();
        lblDescription = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblCategory = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblQuantity = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnEditItem = new javax.swing.JButton();
        btnDeleteItem = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnDecrease = new javax.swing.JButton();
        btnIncrease = new javax.swing.JButton();
        btnViewTrans = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Items");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItemsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblItems);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jLabel1.setText("Search: ");

        jLabel2.setText("Search by: ");

        btnGroupSearch.add(radBtnItemID);
        radBtnItemID.setText("Item ID");
        radBtnItemID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnItemIDActionPerformed(evt);
            }
        });

        btnGroupSearch.add(radBtnName);
        radBtnName.setText("Name");
        radBtnName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnNameActionPerformed(evt);
            }
        });

        btnGroupSearch.add(radBtnDescription);
        radBtnDescription.setText("Description");
        radBtnDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnDescriptionActionPerformed(evt);
            }
        });

        btnGroupSearch.add(radBtnCategory);
        radBtnCategory.setText("Category");
        radBtnCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radBtnName)
                            .addComponent(radBtnItemID))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radBtnCategory)
                            .addComponent(radBtnDescription))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(radBtnItemID)
                    .addComponent(radBtnDescription))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radBtnName)
                    .addComponent(radBtnCategory))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Item Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 0, 15), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Item ID");

        lblItemID.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblItemID.setForeground(new java.awt.Color(0, 51, 153));
        lblItemID.setText("---------");

        lblDescription.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblDescription.setForeground(new java.awt.Color(0, 51, 153));
        lblDescription.setText("---------");

        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Description");

        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Name");

        lblName.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblName.setForeground(new java.awt.Color(0, 51, 153));
        lblName.setText("---------");

        lblCategory.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblCategory.setForeground(new java.awt.Color(0, 51, 153));
        lblCategory.setText("---------");

        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Category");

        lblQuantity.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblQuantity.setForeground(new java.awt.Color(0, 51, 153));
        lblQuantity.setText("---------");

        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Quantity");

        lblPrice.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblPrice.setForeground(new java.awt.Color(0, 51, 153));
        lblPrice.setText("---------");

        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Unit Price(Php)");

        btnEditItem.setText("Edit");
        btnEditItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditItemActionPerformed(evt);
            }
        });

        btnDeleteItem.setText("Delete");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(lblItemID, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(lblCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(lblQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE))
                    .addComponent(lblDescription, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditItem, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDeleteItem, btnEditItem});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblItemID))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblName)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCategory))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblDescription)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditItem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDeleteItem, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQuantity)
                        .addContainerGap())))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblCategory, lblDescription, lblItemID, lblName, lblPrice, lblQuantity});

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Action", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Verdana", 0, 15))); // NOI18N

        btnDecrease.setBackground(new java.awt.Color(255, 0, 0));
        btnDecrease.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDecrease.setText("Decrease");
        btnDecrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDecreaseActionPerformed(evt);
            }
        });

        btnIncrease.setBackground(new java.awt.Color(51, 255, 0));
        btnIncrease.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnIncrease.setText("Increase");
        btnIncrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncreaseActionPerformed(evt);
            }
        });

        btnViewTrans.setBackground(new java.awt.Color(255, 255, 0));
        btnViewTrans.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnViewTrans.setText("View Recent Transactions");
        btnViewTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTransActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewTrans, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnIncrease, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDecrease)))
                .addContainerGap())
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnDecrease, btnIncrease});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncrease, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDecrease))
                .addGap(18, 18, 18)
                .addComponent(btnViewTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnDecrease, btnIncrease});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 845, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRefresh)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-881)/2, (screenSize.height-649)/2, 881, 649);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        conn = BaseDAO.open();
        populateTable();
    }//GEN-LAST:event_formWindowOpened

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        if(radBtnItemID.isSelected()){
            searchItemID();
        }else if(radBtnName.isSelected()){
            searchName();
        }else if(radBtnDescription.isSelected()){
            searchDescription();
        }else if(radBtnCategory.isSelected()){
            searchCategory();
        }
        
        
    }//GEN-LAST:event_txtSearchKeyReleased

    private void radBtnItemIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnItemIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radBtnItemIDActionPerformed

    private void radBtnNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radBtnNameActionPerformed

    private void radBtnDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radBtnDescriptionActionPerformed

    private void radBtnCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radBtnCategoryActionPerformed

    private void tblItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItemsMouseClicked
        // TODO add your handling code here:
        placeToItemInfo();
        btnDeleteItem.setEnabled(true);
        btnEditItem.setEnabled(true);
        btnIncrease.setEnabled(true);
        btnDecrease.setEnabled(true);
    }//GEN-LAST:event_tblItemsMouseClicked

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "All record of the Item will be deleted. Do "
                + "you want to delete?", "Delete Item", JOptionPane.YES_NO_OPTION);
        
        if(p == 0){
            deleteItem();
            populateTable();
        }else{
        
        }
        
    }//GEN-LAST:event_btnDeleteItemActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void btnEditItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditItemActionPerformed
        // TODO add your handling code here:
        EditItem editItem = new EditItem(this,true);
        
        int row = tblItems.getSelectedRow();
        editItem.setItemCode(tblItems.getValueAt(row, 0).toString());
        editItem.setItemName(tblItems.getValueAt(row, 1).toString());
        editItem.setItemDescription(tblItems.getValueAt(row, 2).toString());
        editItem.setItemQuantity(tblItems.getValueAt(row, 3).toString());
        editItem.setItemUOM(tblItems.getValueAt(row, 4).toString());
        editItem.setItemCategory(tblItems.getValueAt(row, 5).toString());
        editItem.setItemCost(tblItems.getValueAt(row, 6).toString());
        
        editItem.setVisible(true);
        
        
        
    }//GEN-LAST:event_btnEditItemActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnIncreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncreaseActionPerformed
        // TODO add your handling code here:
        WindowIncrease increase = new WindowIncrease(this, true);
        increase.setItemID(lblItemID.getText());
        increase.setItemName(lblName.getText());
        increase.setItemQuantity(lblQuantity.getText());
        String itemUnit = tblItems.getValueAt(tblItems.getSelectedRow(), 4).toString(); // unit of the item to be passed to the WindowDecrease Dialog
        increase.setItemUnit(itemUnit);
        
        // Logged in User
        increase.setCurrentUser(currentUser);
        increase.setVisible(true);
    }//GEN-LAST:event_btnIncreaseActionPerformed

    private void btnViewTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTransActionPerformed
        // TODO add your handling code here:
        ViewTransaction transaction = new ViewTransaction();
        transaction.setVisible(true);
    }//GEN-LAST:event_btnViewTransActionPerformed

    private void btnDecreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDecreaseActionPerformed
        // TODO add your handling code here:
        WindowDecrease decrease = new WindowDecrease(this, true);
        decrease.setItemID(lblItemID.getText());
        decrease.setItemName(lblName.getText());
        decrease.setItemQuantity(lblQuantity.getText());
        String itemUnit = tblItems.getValueAt(tblItems.getSelectedRow(), 4).toString(); // unit of the item to be passed to the WindowDecrease Dialog
        decrease.setItemUnit(itemUnit);
        
        // Logged in User
        decrease.setCurrentUser(currentUser);
        decrease.setVisible(true);
    }//GEN-LAST:event_btnDecreaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewItem().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDecrease;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnEditItem;
    private javax.swing.ButtonGroup btnGroupSearch;
    private javax.swing.JButton btnIncrease;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnViewTrans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lblItemID;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JRadioButton radBtnCategory;
    private javax.swing.JRadioButton radBtnDescription;
    private javax.swing.JRadioButton radBtnItemID;
    private javax.swing.JRadioButton radBtnName;
    private javax.swing.JTable tblItems;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    public String getItemCode() {
        return itemCode;
    }

    public void setCurrentUser(String currentUser) {
        this.currentUser = currentUser;
    }
}
