/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory.view;

import dao.BaseDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Allan Jay Aya-ay
 */
public class ViewTransaction extends javax.swing.JFrame {
    private Connection conn = null;
    private PreparedStatement ps = null;
    private ResultSet rs = null;
    
    /**
     * Creates new form viewTransaction
     */
    public ViewTransaction() {
        initComponents();
    }
    
    private void populateTable(){
        try{
            ps = conn.prepareStatement("SELECT * FROM tbltransaction");
            rs = ps.executeQuery();
            
            tblTransaction.setModel(DbUtils.resultSetToTableModel(rs));
            
            ps.close();
            rs.close();
        }catch(Exception ex){
            System.out.println(ex);
        }
         
    }
    
    private void arrDate(){
        try{
            ps = conn.prepareStatement("SELECT * FROM tbltransaction ORDER BY Date DESC");
            rs = ps.executeQuery();
            
            tblTransaction.setModel(DbUtils.resultSetToTableModel(rs));
            
            ps.close();
            rs.close();
        }catch(Exception ex){
            System.out.println(ex);
        }
    }
    
    private void arrItemID(){
        try{
            ps = conn.prepareStatement("SELECT * FROM tbltransaction ORDER BY ItemID ASC");
            rs = ps.executeQuery();
            
            tblTransaction.setModel(DbUtils.resultSetToTableModel(rs));
            
            ps.close();
            rs.close();
        }catch(Exception ex){
            System.out.println(ex);
        }
    }
    
    private void arrItemName(){
        try{
            ps = conn.prepareStatement("SELECT * FROM tbltransaction ORDER BY ItemName ASC");
            rs = ps.executeQuery();
            
            tblTransaction.setModel(DbUtils.resultSetToTableModel(rs));
            
            ps.close();
            rs.close();
        }catch(Exception ex){
            System.out.println(ex);
        }
    }
    
    private void arrAction(){
        try{
            ps = conn.prepareStatement("SELECT * FROM tbltransaction ORDER BY Action ASC");
            rs = ps.executeQuery();
            
            tblTransaction.setModel(DbUtils.resultSetToTableModel(rs));
            
            ps.close();
            rs.close();
        }catch(Exception ex){
            System.out.println(ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaction = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        radBtnDate = new javax.swing.JRadioButton();
        radBtnItemID = new javax.swing.JRadioButton();
        radBtnItemName = new javax.swing.JRadioButton();
        radBtnAction = new javax.swing.JRadioButton();
        btnOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recent Transaction");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblTransaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTransaction);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sort by: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        btnGroup1.add(radBtnDate);
        radBtnDate.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        radBtnDate.setText("Date");
        radBtnDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radBtnDateActionPerformed(evt);
            }
        });

        btnGroup1.add(radBtnItemID);
        radBtnItemID.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        radBtnItemID.setText("Item ID");

        btnGroup1.add(radBtnItemName);
        radBtnItemName.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        radBtnItemName.setText("Item Name");

        btnGroup1.add(radBtnAction);
        radBtnAction.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        radBtnAction.setText("Action");

        btnOrder.setText("Sort");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radBtnDate)
                    .addComponent(radBtnItemID))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radBtnAction)
                    .addComponent(radBtnItemName))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOrder)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radBtnDate)
                    .addComponent(radBtnItemName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radBtnItemID)
                    .addComponent(radBtnAction))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrder, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        conn = BaseDAO.open();
        populateTable();
    }//GEN-LAST:event_formWindowOpened

    private void radBtnDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radBtnDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radBtnDateActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        // TODO add your handling code here:
        if(radBtnDate.isSelected()){
            arrDate();
        }else if(radBtnItemID.isSelected()){
            arrItemID();
        }else if(radBtnItemName.isSelected()){
            arrItemName();
        }else if(radBtnAction.isSelected()){
            arrAction();
        }
    }//GEN-LAST:event_btnOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewTransaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewTransaction().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup1;
    private javax.swing.JButton btnOrder;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radBtnAction;
    private javax.swing.JRadioButton radBtnDate;
    private javax.swing.JRadioButton radBtnItemID;
    private javax.swing.JRadioButton radBtnItemName;
    private javax.swing.JTable tblTransaction;
    // End of variables declaration//GEN-END:variables
}
